@ignore
@Especificacao.Pedido.Passo60
Feature: Gerar_t_PEDIDO_ITEM

Scenario: Gerar_t_PEDIDO_ITEM
	#loja/PedidoNovoConfirma.asp
	#de linha 2088
	#s="SELECT * FROM t_PEDIDO_ITEM WHERE pedido='X'"
	#até linha
	#rs("descontinuado") = .descontinuado
	#rs.Update
	Given Pedido base
	Then Sem nenhum erro
	#item 1
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "1", verificar campo "fabricante" = "003"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "1", verificar campo "produto" = "003220"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "1", verificar campo "qtde" = "2"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "1", verificar campo "desc_dado" = "0"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "1", verificar campo "preco_venda" = "659.600"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "1", verificar campo "preco_fabricante" = "659.300"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "1", verificar campo "preco_lista" = "659.600"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "1", verificar campo "margem" = "0.0"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "1", verificar campo "desc_max" = "8.0"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "1", verificar campo "comissao" = "0.0"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "1", verificar campo "descricao" = "Evap. AR09MVSPBGMNAZ Inverter - FRIO"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "1", verificar campo "ean" = "7892509093149"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "1", verificar campo "grupo" = "INV"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "1", verificar campo "peso" = "10.2"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "1", verificar campo "qtde_volumes" = "1"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "1", verificar campo "abaixo_min_status" = "0"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "1", verificar campo "abaixo_min_autorizacao" = ""
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "1", verificar campo "abaixo_min_autorizador" = ""
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "1", verificar campo "sequencia" = "1"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "1", verificar campo "markup_fabricante" = "0"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "1", verificar campo "preco_NF" = "694.0500"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "1", verificar campo "abaixo_min_superv_autorizador" = ""
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "1", verificar campo "vl_custo2" = "0.0000"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "1", verificar campo "descricao_html" = "Evap. <b>AR09MVS</b>PBGMNAZ Inverter - FRIO"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "1", verificar campo "custoFinancFornecCoeficiente" = "1.0527"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "1", verificar campo "custoFinancFornecPrecoListaBase" = "626.5800"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "1", verificar campo "cubagem" = "0.09"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "1", verificar campo "ncm" = "84151011"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "1", verificar campo "cst" = "000"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "1", verificar campo "separacao_rel_nsu" = "0"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "1", verificar campo "separacao_data" = "null"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "1", verificar campo "separacao_data_hora" = "null"                                        
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "1", verificar campo "separacao_deposito_zona_id" = "0"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "1", verificar campo "descontinuado" = ""
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "1", verificar campo "subgrupo" = "null"
	#item 2
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "2", verificar campo "fabricante" = "003"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "2", verificar campo "produto" = "003221"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "2", verificar campo "qtde" = "2"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "2", verificar campo "desc_dado" = "0"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "2", verificar campo "preco_venda" = "989.4000"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "2", verificar campo "preco_fabricante" = "988.9500"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "2", verificar campo "preco_lista" = "939.8700"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "2", verificar campo "margem" = "0.0"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "2", verificar campo "desc_max" = "8.0"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "2", verificar campo "comissao" = "0.0"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "2", verificar campo "descricao" = "Cond. AR09MVSPBGMXAZ Inverter - FRIO"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "2", verificar campo "ean" = "7892509093156"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "2", verificar campo "grupo" = "INV"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "2", verificar campo "peso" = "29.5"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "2", verificar campo "qtde_volumes" = "1"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "2", verificar campo "abaixo_min_status" = "0"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "2", verificar campo "abaixo_min_autorizacao" = ""
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "2", verificar campo "abaixo_min_autorizador" = ""
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "2", verificar campo "sequencia" = "2"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "2", verificar campo "markup_fabricante" = "0"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "2", verificar campo "preco_NF" = "1041.0700"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "2", verificar campo "abaixo_min_superv_autorizador" = ""
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "2", verificar campo "vl_custo2" = "0.0000"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "2", verificar campo "descricao_html" = "Cond. <b>AR09MVS</b>PBGMXAZ Inverter - FRIO"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "2", verificar campo "custoFinancFornecCoeficiente" = "1.0527"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "2", verificar campo "custoFinancFornecPrecoListaBase" = "939.8700"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "2", verificar campo "cubagem" = "0.19"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "2", verificar campo "ncm" = "84151011"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "2", verificar campo "cst" = "000"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "2", verificar campo "separacao_rel_nsu" = "0"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "2", verificar campo "separacao_data" = "null"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "2", verificar campo "separacao_data_hora" = "null"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "2", verificar campo "separacao_deposito_zona_id" = "0"
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "2", verificar campo "descontinuado" = ""
	And Tabela "t_PEDIDO_ITEM" registro criado e campo "sequencia" = "2", verificar campo "subgrupo" = "null"
