export class DadosClienteCadastroDto {
    Loja: string;
    Indicador_Orcamentista: string;
    Vendedor: string;
    Id: string;
    Cnpj_Cpf: string;
    Rg: string;
    Ie: string;
    Contribuinte_Icms_Status: number;
    Tipo: string;
    Observacao_Filiacao: string;
    Nascimento: Date | string | null;
    Sexo: string;
    Nome: string;
    ProdutorRural: number;
    Endereco: string;
    Numero: string;
    Complemento: string;
    Bairro: string;
    Cidade: string;
    Uf: string;
    Cep: string;
    DddResidencial: string;
    TelefoneResidencial: string;
    DddComercial: string;
    TelComercial: string;
    Ramal: string;
    DddCelular: string;
    Celular: string;
    TelComercial2: string;
    DddComercial2: string;
    Ramal2: string;
    Email: string;
    EmailXml: string;
    Contato: string;
}
