stages:
  - build
  - release
  
variables:
  apiOrcamento: "OrcamentoCotacaoApi/OrcamentoCotacaoApi"
  configuration: "Debug"
  caminhoImplantacao: "\\\\10.255.0.30\\ArClube.OrcamentoCotacaoAPI\\publish"
  caminhoPublicacao: "publish"
  nomePacote: "API"

before_script:
  - "cd ${apiOrcamento}"

build:
  stage: build
  image: mcr.microsoft.com/dotnet/core/sdk:3.1
  script:
    - dotnet restore
    - dotnet build --no-restore --configuration ${configuration}
  #artifacts:
  #  paths:
  #  - "bin/"
  #  expire_in: 1 week    
  allow_failure: true

release:
  stage: release
  #only:
  #  - develop
  #artifacts:
  #  paths:
  #      - /release
  #  expire_in: 1 week
  image: mcr.microsoft.com/dotnet/core/sdk:3.1
  script:
    #- ls ../publish
    #- cp $caminhoPublicacao/* $caminhoImplantacao
    #- "cd ${apiOrcamento}"    
    #- ls
    - dotnet publish --output ${caminhoPublicacao}
    - apt-get update -qq && apt-get install -y -qq zip 
    - zip -r ${nomePacote} ${caminhoPublicacao}
    - ls *.zip
  allow_failure: true
