stages:
  - build
  - test

variables:
  teste: "Source/UnitTest.Integration.Repositories"
  loja: "/Loja/Loja.UI/Loja.UI.csproj"
  #MSSQL_HOST: microsoft-mssql-server-linux
  #ACCEPT_EULA: "Y"
  #SA_PASSWORD: yourStrong(!)Password

before_script:
    - ""
  

build:
  stage: build
  image: mcr.microsoft.com/dotnet/core/sdk:3.1
  script:
      - "cd $loja"
      - "dotnet restore"
      - "dotnet build"
  only:
    - automacoes

test:
  stage: test
  image: mcr.microsoft.com/dotnet/core/sdk:3.1
  script: 
      - "cd $teste"
      - "dotnet test"
  allow_failure: false
  only:
    - automacoes