export class Constantes {
    //' CÓDIGOS QUE IDENTIFICAM SE É PESSOA FÍSICA OU JURÍDICA
    public static ID_PF = "PF";
    public static ID_PJ = "PJ"

    //'	NÚMERO DE LINHAS DO CAMPO "OBS I" DO PEDIDO
    public static MAX_LINHAS_OBS1 = 5;

    //'   NÚMERO DE LINHAS DO CAMPO "TEXTO CONSTAR NF" DO PEDIDO
    public static MAX_LINHAS_NF_TEXTO_CONSTAR = 2;

    //' CÓDIGOS P/ ENTREGA IMEDIATA
    public static COD_ETG_IMEDIATA_ST_INICIAL = 0;
    public static COD_ETG_IMEDIATA_NAO = 1;
    public static COD_ETG_IMEDIATA_SIM = 2;
    public static COD_ETG_IMEDIATA_NAO_DEFINIDO = 10;  //' PEDIDOS ANTIGOS QUE JÁ ESTAVAM NA BASE

    // ' CÓDIGOS P/ FLAG "BEM DE USO/CONSUMO"
    public static COD_ST_BEM_USO_CONSUMO_NAO = 0;
    public static COD_ST_BEM_USO_CONSUMO_SIM = 1;
    public static COD_ST_BEM_USO_CONSUMO_NAO_DEFINIDO = 10;//  ' PEDIDOS ANTIGOS QUE JÁ ESTAVAM NA BASE


    // '	CÓDIGOS PARA O CAMPO "INSTALADOR INSTALA"
    public static COD_INSTALADOR_INSTALA_NAO_DEFINIDO = 0;
    public static COD_INSTALADOR_INSTALA_NAO = 1;
    public static COD_INSTALADOR_INSTALA_SIM = 2;

    //' CÓDIGOS P/ STATUS QUE INDICA SE CLIENTE É OU NÃO CONTRIBUINTE DO ICMS
    public static COD_ST_CLIENTE_CONTRIBUINTE_ICMS_INICIAL = 0;
    public static COD_ST_CLIENTE_CONTRIBUINTE_ICMS_NAO = 1;
    public static COD_ST_CLIENTE_CONTRIBUINTE_ICMS_SIM = 2;
    public static COD_ST_CLIENTE_CONTRIBUINTE_ICMS_ISENTO = 3;

    //' CÓDIGOS P/ STATUS QUE INDICA SE CLIENTE É OU NÃO PRODUTOR RURAL
    public static COD_ST_CLIENTE_PRODUTOR_RURAL_INICIAL = 0;
    public static COD_ST_CLIENTE_PRODUTOR_RURAL_NAO = 1;
    public static COD_ST_CLIENTE_PRODUTOR_RURAL_SIM = 2;

    //'	NÚMERO DE LINHAS DO CAMPO "FORMA DE PAGAMENTO" DO PEDIDO
    public static MAX_LINHAS_FORMA_PAGTO = 5;

    //' CÓDIGOS P/ FLAG "GarantiaIndicadorStatus"
    public static COD_GARANTIA_INDICADOR_STATUS__NAO = 0;
    public static COD_GARANTIA_INDICADOR_STATUS__SIM = 1;
    public static COD_GARANTIA_INDICADOR_STATUS__NAO_DEFINIDO = 10; //  ' PEDIDOS ANTIGOS QUE JÁ ESTAVAM NA BASE

    // QUANTIDADE MÁXIMA DE REGISTROS COM OPÇÕES DE PARCELAMENTO P/ CADA FORNECEDOR
    public static MAX_LINHAS_TABELA_CUSTO_FINANCEIRO_FORNECEDOR = 24;
    public static MAX_DECIMAIS_COEFICIENTE_CUSTO_FINANCEIRO_FORNECEDOR = 6;
    public static COD_CUSTO_FINANC_FORNEC_TIPO_PARCELAMENTO__SEM_ENTRADA = "SE";
    public static COD_CUSTO_FINANC_FORNEC_TIPO_PARCELAMENTO__COM_ENTRADA = "CE";
    public static COD_CUSTO_FINANC_FORNEC_TIPO_PARCELAMENTO__A_VISTA = "AV";

    //FORMA DE PAGAMENTO
    public static COD_FORMA_PAGTO_A_VISTA = "1";
    public static COD_FORMA_PAGTO_PARCELADO_CARTAO = "2";
    public static COD_FORMA_PAGTO_PARCELADO_COM_ENTRADA = "3";
    public static COD_FORMA_PAGTO_PARCELADO_SEM_ENTRADA = "4";
    public static COD_FORMA_PAGTO_PARCELA_UNICA = "5";
    public static COD_FORMA_PAGTO_PARCELADO_CARTAO_MAQUINETA = "6";

    //Percentual de deságio para RA Líquida
    public static PERC_DESAGIO_RA_LIQUIDA: number = 25;

    public static ID_FORMA_PAGTO_CARTAO = "5";
    public static ID_FORMA_PAGTO_CARTAO_MAQUINETA = "7";

    //TAMANHO MÁXIMO DO CAMPO ENDEREÇO DEVIDO À RESTRIÇÃO EXISTENTE NA NOTA FISCAL ELETRÔNICA
    public static MAX_TAMANHO_CAMPO_ENDERECO = 60
    public static MAX_TAMANHO_CAMPO_ENDERECO_NUMERO = 60
    public static MAX_TAMANHO_CAMPO_ENDERECO_COMPLEMENTO = 60
    public static MAX_TAMANHO_CAMPO_ENDERECO_BAIRRO = 60
    public static MAX_TAMANHO_CAMPO_ENDERECO_CIDADE = 60
}

